[server]
maxUploadSize = 1024
runOnSave = false
maxMessageSize = 1024
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[global]
developmentMode = false

[logger]
level = "error"

